/** Autogenerated Main.cpp. */

// ================================| Include only the DSP files  |================================

#include <AppConfig.h>
#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// ==========================| Now we can add the rest of the codebase |==========================

#include <JuceHeader.h>

#if !JUCE_WINDOWS
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"
#endif

// ======================================| Project Factory |======================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -------------------------------------------------------------------
		
		registerPolyNode<project::gran<1>, scriptnode::wrap::illegal_poly<project::gran<1>>>();
		registerPolyNode<project::comb2<1>, scriptnode::wrap::illegal_poly<project::comb2<1>>>();
		registerPolyNode<project::comb<1>, scriptnode::wrap::illegal_poly<project::comb<1>>>();
		registerPolyNode<project::Arrange<1>, wrap::illegal_poly<project::Arrange<1>>>();
		registerPolyNode<project::dtest<1>, wrap::illegal_poly<project::dtest<1>>>();
		registerPolyNode<project::res1<1>, wrap::illegal_poly<project::res1<1>>>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::_networkdata>();
		registerDataNode<project::FinStack_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* scriptnode::DspNetwork::createStaticFactory()
{
	return new project::Factory();
}

#if !JUCE_WINDOWS
#pragma clang diagnostic pop
#endif


